### ISSUE TITLE
openCTF platform is in rust now

### ISSUE THREAD

**Issue by mzfr** [We5ter/Awesome-Platforms#2]
On [line 19](https://github.com/We5ter/Awesome-Platforms/blob/master/CTF-Platforms.md#L19) of CTF platform, the name refers to openctf but the URL takes you to [librectf](https://github.com/easyctf/librectf) and is not written in python but Rust

**Comment by We5ter** [comment]
Yeah, maybe the author edited repository name and its code, anyway, thank you for such a warm reminder, I have updated the `CTF-Platforms.md`.
